/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Meu Computador
 */
public class Menu_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Menu_GUI
     */
    public Menu_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        menuV1_btn = new javax.swing.JButton();
        menuV2_btn = new javax.swing.JButton();
        sair_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(240, 248, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Impact", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(135, 206, 250));
        jLabel2.setText("Vôos Disponíveis");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 10, 200, 90);

        jLabel3.setBackground(new java.awt.Color(135, 206, 250));
        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Vôo 500 - Rio de Janeiro >> São Paulo ");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(135, 206, 250), 5, true));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 100, 270, 80);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Vôo 500 - São Paulo >> Rio de Janeiro");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(135, 206, 250), 5, true));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setMaximumSize(new java.awt.Dimension(264, 26));
        jLabel4.setMinimumSize(new java.awt.Dimension(264, 26));
        jLabel4.setPreferredSize(new java.awt.Dimension(252, 26));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 220, 270, 80);

        menuV1_btn.setBackground(new java.awt.Color(135, 206, 250));
        menuV1_btn.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        menuV1_btn.setText("Reservar");
        menuV1_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuV1_btnActionPerformed(evt);
            }
        });
        jPanel1.add(menuV1_btn);
        menuV1_btn.setBounds(320, 120, 120, 40);

        menuV2_btn.setBackground(new java.awt.Color(135, 206, 250));
        menuV2_btn.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        menuV2_btn.setText("Reservar");
        menuV2_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuV2_btnActionPerformed(evt);
            }
        });
        jPanel1.add(menuV2_btn);
        menuV2_btn.setBounds(320, 240, 120, 40);

        sair_btn.setBackground(new java.awt.Color(135, 206, 250));
        sair_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sair_btn.setText("X");
        sair_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair_btnActionPerformed(evt);
            }
        });
        jPanel1.add(sair_btn);
        sair_btn.setBounds(560, 20, 50, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/plane.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(450, 120, 200, 160);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(640, 360));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuV1_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuV1_btnActionPerformed
        dispose();
        new Voo1_GUI().setVisible(true);
    }//GEN-LAST:event_menuV1_btnActionPerformed

    private void menuV2_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuV2_btnActionPerformed
        dispose();
        new Voo2_GUI().setVisible(true);
    }//GEN-LAST:event_menuV2_btnActionPerformed

    private void sair_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_btnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sair_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JButton menuV1_btn;
    public static javax.swing.JButton menuV2_btn;
    public static javax.swing.JButton sair_btn;
    // End of variables declaration//GEN-END:variables
}
