/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Meu Computador
 */
public class Voo1_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Voo1_GUI
     */
    public Voo1_GUI() {
        initComponents();
        Model.Funcoes_DAO.exibir1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();
        a2 = new javax.swing.JLabel();
        a3 = new javax.swing.JLabel();
        a4 = new javax.swing.JLabel();
        a5 = new javax.swing.JLabel();
        a6 = new javax.swing.JLabel();
        assento1_lbl = new javax.swing.JLabel();
        assento2_lbl = new javax.swing.JLabel();
        assento3_lbl = new javax.swing.JLabel();
        assento4_lbl = new javax.swing.JLabel();
        assento5_lbl = new javax.swing.JLabel();
        assento6_lbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        escolha_txt = new javax.swing.JTextField();
        reservarV1_btn = new javax.swing.JButton();
        msg_lbl = new javax.swing.JLabel();
        voltar1_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(240, 248, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Impact", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(135, 206, 250));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Rio de Janeiro >> São Paulo");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 20, 310, 40);

        jLabel1.setFont(new java.awt.Font("Impact", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(135, 206, 250));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vôo 500");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(280, 60, 90, 40);

        a1.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        a1.setText("2 [     ]");
        jPanel1.add(a1);
        a1.setBounds(390, 120, 70, 26);

        a2.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        a2.setText("4 [     ]");
        jPanel1.add(a2);
        a2.setBounds(390, 160, 70, 26);

        a3.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        a3.setText("1 [     ]");
        jPanel1.add(a3);
        a3.setBounds(180, 120, 70, 26);

        a4.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        a4.setText("6 [     ]");
        jPanel1.add(a4);
        a4.setBounds(390, 200, 70, 26);

        a5.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        a5.setText("3 [     ]");
        jPanel1.add(a5);
        a5.setBounds(180, 160, 70, 26);

        a6.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        a6.setText("5 [     ]");
        jPanel1.add(a6);
        a6.setBounds(180, 200, 70, 26);

        assento1_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        assento1_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(assento1_lbl);
        assento1_lbl.setBounds(202, 122, 30, 20);

        assento2_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        assento2_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(assento2_lbl);
        assento2_lbl.setBounds(412, 122, 30, 20);

        assento3_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        assento3_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(assento3_lbl);
        assento3_lbl.setBounds(202, 162, 30, 20);

        assento4_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        assento4_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(assento4_lbl);
        assento4_lbl.setBounds(412, 162, 30, 20);

        assento5_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        assento5_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(assento5_lbl);
        assento5_lbl.setBounds(202, 202, 30, 20);

        assento6_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        assento6_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(assento6_lbl);
        assento6_lbl.setBounds(412, 202, 30, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel3.setText("Assento");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(170, 275, 80, 20);

        escolha_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escolha_txtActionPerformed(evt);
            }
        });
        jPanel1.add(escolha_txt);
        escolha_txt.setBounds(250, 270, 120, 30);

        reservarV1_btn.setBackground(new java.awt.Color(135, 206, 250));
        reservarV1_btn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        reservarV1_btn.setText("RESERVAR");
        reservarV1_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservarV1_btnActionPerformed(evt);
            }
        });
        jPanel1.add(reservarV1_btn);
        reservarV1_btn.setBounds(380, 270, 90, 30);

        msg_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(msg_lbl);
        msg_lbl.setBounds(180, 310, 300, 30);

        voltar1_btn.setBackground(new java.awt.Color(135, 206, 250));
        voltar1_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        voltar1_btn.setText("VOLTAR");
        voltar1_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar1_btnActionPerformed(evt);
            }
        });
        jPanel1.add(voltar1_btn);
        voltar1_btn.setBounds(30, 320, 80, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(640, 360));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void escolha_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escolha_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_escolha_txtActionPerformed

    private void reservarV1_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservarV1_btnActionPerformed
        Model.Funcoes_DAO.reservar1();
    }//GEN-LAST:event_reservarV1_btnActionPerformed

    private void voltar1_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar1_btnActionPerformed
        dispose();
        new Menu_GUI().setVisible(true);
    }//GEN-LAST:event_voltar1_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Voo1_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Voo1_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Voo1_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Voo1_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Voo1_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a3;
    private javax.swing.JLabel a4;
    private javax.swing.JLabel a5;
    private javax.swing.JLabel a6;
    public static javax.swing.JLabel assento1_lbl;
    public static javax.swing.JLabel assento2_lbl;
    public static javax.swing.JLabel assento3_lbl;
    public static javax.swing.JLabel assento4_lbl;
    public static javax.swing.JLabel assento5_lbl;
    public static javax.swing.JLabel assento6_lbl;
    public static javax.swing.JTextField escolha_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel msg_lbl;
    public static javax.swing.JButton reservarV1_btn;
    public static javax.swing.JButton voltar1_btn;
    // End of variables declaration//GEN-END:variables
}
