/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Meu Computador
 */
public class Voo2_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Voo2_GUI
     */
    public Voo2_GUI() {
        initComponents();
        Model.Funcoes_DAO.exibir2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        a3 = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();
        a5 = new javax.swing.JLabel();
        a2 = new javax.swing.JLabel();
        a6 = new javax.swing.JLabel();
        a4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        escolha2_txt = new javax.swing.JTextField();
        reservarV2_btn = new javax.swing.JButton();
        assento01_lbl = new javax.swing.JLabel();
        assento02_lbl = new javax.swing.JLabel();
        assento03_lbl = new javax.swing.JLabel();
        assento04_lbl = new javax.swing.JLabel();
        assento05_lbl = new javax.swing.JLabel();
        assento06_lbl = new javax.swing.JLabel();
        msg2_lbl = new javax.swing.JLabel();
        voltar2_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(240, 248, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Impact", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(135, 206, 250));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("São Paulo >> Rio de Janeiro");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 20, 310, 40);

        jLabel1.setFont(new java.awt.Font("Impact", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(135, 206, 250));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vôo 501");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(280, 60, 90, 40);

        a3.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        a3.setText("1 [     ]");
        jPanel1.add(a3);
        a3.setBounds(180, 120, 70, 26);

        a1.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        a1.setText("2 [     ]");
        jPanel1.add(a1);
        a1.setBounds(390, 120, 70, 26);

        a5.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        a5.setText("3 [     ]");
        jPanel1.add(a5);
        a5.setBounds(180, 160, 70, 26);

        a2.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        a2.setText("4 [     ]");
        jPanel1.add(a2);
        a2.setBounds(390, 160, 70, 26);

        a6.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        a6.setText("5 [     ]");
        jPanel1.add(a6);
        a6.setBounds(180, 200, 70, 26);

        a4.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        a4.setText("6 [     ]");
        jPanel1.add(a4);
        a4.setBounds(390, 200, 70, 26);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel3.setText("Assento");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(170, 275, 80, 20);

        escolha2_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escolha2_txtActionPerformed(evt);
            }
        });
        jPanel1.add(escolha2_txt);
        escolha2_txt.setBounds(250, 270, 120, 30);

        reservarV2_btn.setBackground(new java.awt.Color(135, 206, 250));
        reservarV2_btn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        reservarV2_btn.setText("RESERVAR");
        reservarV2_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservarV2_btnActionPerformed(evt);
            }
        });
        jPanel1.add(reservarV2_btn);
        reservarV2_btn.setBounds(380, 270, 90, 30);

        assento01_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        assento01_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(assento01_lbl);
        assento01_lbl.setBounds(202, 122, 30, 20);

        assento02_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        assento02_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(assento02_lbl);
        assento02_lbl.setBounds(412, 122, 30, 20);

        assento03_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        assento03_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(assento03_lbl);
        assento03_lbl.setBounds(202, 162, 30, 20);

        assento04_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        assento04_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(assento04_lbl);
        assento04_lbl.setBounds(412, 162, 30, 20);

        assento05_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        assento05_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(assento05_lbl);
        assento05_lbl.setBounds(202, 202, 30, 20);

        assento06_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        assento06_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(assento06_lbl);
        assento06_lbl.setBounds(412, 202, 30, 20);

        msg2_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(msg2_lbl);
        msg2_lbl.setBounds(180, 310, 300, 30);

        voltar2_btn.setBackground(new java.awt.Color(135, 206, 250));
        voltar2_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        voltar2_btn.setText("VOLTAR");
        voltar2_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar2_btnActionPerformed(evt);
            }
        });
        jPanel1.add(voltar2_btn);
        voltar2_btn.setBounds(30, 320, 80, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(640, 360));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void escolha2_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escolha2_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_escolha2_txtActionPerformed

    private void reservarV2_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservarV2_btnActionPerformed
        Model.Funcoes_DAO.reservar2();
    }//GEN-LAST:event_reservarV2_btnActionPerformed

    private void voltar2_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar2_btnActionPerformed
        dispose();
        new Menu_GUI().setVisible(true);
    }//GEN-LAST:event_voltar2_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Voo2_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Voo2_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Voo2_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Voo2_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Voo2_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a3;
    private javax.swing.JLabel a4;
    private javax.swing.JLabel a5;
    private javax.swing.JLabel a6;
    public static javax.swing.JLabel assento01_lbl;
    public static javax.swing.JLabel assento02_lbl;
    public static javax.swing.JLabel assento03_lbl;
    public static javax.swing.JLabel assento04_lbl;
    public static javax.swing.JLabel assento05_lbl;
    public static javax.swing.JLabel assento06_lbl;
    public static javax.swing.JTextField escolha2_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel msg2_lbl;
    public static javax.swing.JButton reservarV2_btn;
    public static javax.swing.JButton voltar2_btn;
    // End of variables declaration//GEN-END:variables
}
